/*
 * Copyright (c) 2024 The Regents of The University of Michigan
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met: redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer;
 * redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution;
 * neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "cpu/probes/bb_profiler.hh"

#include <algorithm>
#include <fstream>
#include <iomanip>
#include <regex>
#include <sstream>
#include <string>

#include "base/callback.hh"
#include "base/logging.hh"
#include "base/statistics.hh"
#include "base/trace.hh"
#include "cpu/base.hh"
#include "cpu/static_inst.hh"
#include "cpu/thread_context.hh"
#include "debug/BBProfiler.hh"
#include "sim/core.hh"
#include "sim/sim_exit.hh"

namespace gem5
{

BBProfiler::BBProfiler(const BBProfilerParams &params)
    : ProbeListenerObject(params),
      outputFile(params.output_file),
      lastBBId(""),
      lastBBTime(0),
      active(true)
{
    DPRINTF(BBProfiler, "BBProfiler created with output file: %s\n",
            outputFile);

    // Register a callback to write results when simulation ends
    registerExitCallback([this]() { writeResults(); });
}

BBProfiler::~BBProfiler()
{
    // Make sure results are written when the profiler is destroyed
    writeResults();
}

void
BBProfiler::regProbeListeners()
{
    // Register a listener for the CommittedInst probe point
    // This will be called for every committed instruction
    listeners.push_back(new BBProfilerListener(
        this, "CommittedInst", &BBProfiler::committedInstHandler));
}

void
BBProfiler::committedInstHandler(const std::pair<const StaticInstPtr, Addr> &inst_pc)
{
    if (!active) {
        DPRINTF(BBProfiler, "BBProfiler is not active\n");
        return;
    }
    

    // Get the current time
    Tick currentTime = curTick();

    // Extract the instruction and PC from the pair
    const StaticInstPtr &inst = inst_pc.first;
    Addr pc_addr = inst_pc.second;

    // Get the PC address as a string
    std::stringstream ss;
    ss << "0x" << std::hex << pc_addr;
    std::string pc_str = ss.str();

    // Check if this instruction is a basic block marker
    std::string bbid;
    if (isBBMarkerInst(inst, bbid)) {
        DPRINTF(BBProfiler, "Found basic block marker: %s at PC %s\n",
                bbid, pc_str);

        // Increment the count for this basic block
        bbCounts[bbid]++;

        // If we've seen a previous basic block, update its time
        if (!lastBBId.empty()) {
            bbTimes[lastBBId] += (currentTime - lastBBTime);
        }

        // Update the last seen basic block
        lastBBId = bbid;
        lastBBTime = currentTime;
    } else {
      DPRINTF(BBProfiler, "Not a basic block marker: %s at PC %s\n",
              inst->disassemble(pc_addr), pc_str);
    }
}

bool
BBProfiler::isBBMarkerInst(const StaticInstPtr &inst, std::string &bbid)
{
    // Get the disassembly of the instruction
    // We need to provide a dummy PC and symbol table
    Addr dummy_pc = 0;
    const loader::SymbolTable *dummy_symtab = nullptr;
    std::string disasm = inst->disassemble(dummy_pc, dummy_symtab);

    // Check if it matches the pattern "movq bbid#..."
    // This is a simplified check and might need to be adjusted based on
    // the actual assembly generated by the LLVM pass
    std::regex bbMarkerPattern(R"(movq\s+\"bbid#([^\"]+)\"@GOTPCREL\(%rip\),\s+%rax)");
    std::smatch match;

    if (std::regex_search(disasm, match, bbMarkerPattern)) {
        if (match.size() > 1) {
            bbid = match[1].str();
            return true;
        }
    }

    return false;
}

void
BBProfiler::writeResults()
{
    // Only write results once
    if (!active)
        return;
    active = false;

    // If we've seen a previous basic block, update its time
    if (!lastBBId.empty()) {
        bbTimes[lastBBId] += (curTick() - lastBBTime);
    }

    // Open the output file
    std::ofstream outFile(outputFile);
    if (!outFile.is_open()) {
        warn("BBProfiler: Could not open output file %s\n", outputFile);
        return;
    }

    // Write the header
    outFile << "Basic Block ID,Execution Count,Total Time (ticks),Average Time (ticks)\n";

    // Write the data for each basic block
    for (const auto &entry : bbCounts) {
        const std::string &bbid = entry.first;
        uint64_t count = entry.second;
        Tick totalTime = bbTimes[bbid];
        double avgTime = count > 0 ? static_cast<double>(totalTime) / count : 0.0;

        outFile << bbid << "," << count << "," << totalTime << "," << std::fixed
                << std::setprecision(2) << avgTime << "\n";
    }

    outFile.close();
    inform("BBProfiler: Results written to %s\n", outputFile);
}

} // namespace gem5 